image: debian:stretch

cache:
  paths:
    - vendor/apt

stages:
  - build
  - deploy

before_script:
  - mkdir -p vendor/apt
  - apt -o dir::cache::archives="vendor/apt" update && apt install -o dir::cache::archives="vendor/apt" -y android-sdk android-sdk-platform-23 git libgradle-android-plugin-java
  - export ANDROID_HOME=/usr/lib/android-sdk

debug:
  stage: build
  only:
    - branches
  except:
    - master
  script: ./gradlew assembleDebug

release:
  stage: build
  only:
    - master
  script: ./gradlew assembleRelease

DEPLOY:
  stage: deploy
  only:
    - master
  script:
    - echo -n "Do Deployment here"
